[package]
name = "line-notify-api-rust"
version = "0.1.0"
authors = ["uma0317 <blog3170@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.2"